### ISSUE TITLE
[Deploy] Todoist

### ISSUE THREAD

**Issue by avatarkava** [meetfranz/plugins#1]
### Service
Todoist (www.todoist.com)

### Link to your repository
https://github.com/avatarkava/recipe-todoist

**Comment by adlk** [comment]
Waiting for the fix before deploying https://github.com/avatarkava/recipe-todoist/issues/1

**Comment by avatarkava** [comment]
Should be fixed. 

The implementation does have some opinionated choices about what counters to include on the badge, so I'm open to input on those.

**Comment by adlk** [comment]
I haven't checked your package.json earlier. There is nothing wrong with it but I did a cleanup PR (https://github.com/avatarkava/recipe-todoist/pull/2) to remove unnecessary config flags - as most of them either do nothing (because of legacy) or are set by default

**Comment by avatarkava** [comment]
Merged down - as you suspected, I had pulled the package.json from a legacy version of the project.

**Comment by adlk** [comment]
Deployed 🎉
