### ISSUE TITLE
Custom tabs do not survive a restart

### ISSUE THREAD

**Issue by Lazza** [meetfranz/plugins#10]
Yesterday I was using my custom Glip plugin posted in #2 and it was all fine. Today I realized that after closing Franz, my Glip tab was gone. I re-added it and tried to close Franz. Same issue again.

While Franz is open, the tab works fine (including the message count) but it doesn't get saved.

**Comment by Retzudo** [comment]
Can confirm. Just had the same realization with my Teamwork plugin.

**Comment by ffflorian** [comment]
Same here.

System: Ubuntu 15.10 x64, Franz 4.0.0 Build 35

**Comment by thepaperpilot** [comment]
It's not saving any new tabs for me. I don't know how else to tell franz, since they don't have an issue tracker on the app repository, and no gitter or anything.

I'm on Ubuntu 15.10 x64, upgrading to Franz 4.0.1 did not solve the issue for me.

**Comment by merlinschumacher** [comment]
I second that. I'm on Arch

**Comment by kr3v** [comment]
This is just on 4.0.*, 3.1.1 works nice. Also, I can't add non-custom tabs, for example Slack e.t.c.

Windows version works fine (it's just in addition to the above).

**Comment by Lazza** [comment]
> I don't know how else to tell franz, since they don't have an issue tracker on the app repository, and no gitter or anything

Indeed. It's quite astonishing how they basically made a small wrapper using Electron and decided to keep it closed-source.

> This is just on 4.0.*

Yes, previous versions did not have custom tabs so they can't be broken I guess. :blush:

**Comment by kr3v** [comment]
> Yes, previous versions did not have custom tabs so they can't be broken I guess. 
> Also, I can't add non-custom tabs, for example Slack e.t.c.
According to this. I wasn't able to add Slack or Skype services in 4.0.0 on Linux, I did it only using 3.1.1.

**Comment by Lazza** [comment]
Ah sorry, I get your point now.

**Comment by ffflorian** [comment]
I installed Franz 4.0.2 today and it seems to be fixed.

**Comment by adlk** [comment]
Thanks guys for reporting this issue. Unfortunately two bugs slipped in and are now fixed with 4.0.2.
