### ISSUE TITLE
MightyText recipe on Franz Mac doesn't appear

### ISSUE THREAD

**Issue by MijoBarbaric** [meetfranz/plugins#134]
Hi guys

First of all thanks for Franz, it is such a great app! For me there is one service missing, which is MightyText. I wanted to make an own recipe to integrate it and then I found this repository:

https://github.com/brianjohnhanna/mightytext-franz-recipe

Everything seems included and from my point of view correct. I followed the instructions on how to make a recipe work on my local machine (dev) but unfortunately it doesn't appear in the service list at all.

I'm on a Mac High Sierra 10.13.3

The folder `Franz` under `/Library/Application Support` was missing in the first place, so I created the following folder structure

`/Library/Application Support/Franz/recipes/dev/mightytext`

and copied all files from the above mentioned repository.

Quit and restarted Franz, nothing happens. The service is not listed anywhere.

Am I missing something? Thanks in advance!

**Comment by brianjohnhanna** [comment]
@MijoBarbaric There has been an [open issue](https://github.com/meetfranz/plugins/issues/50) here for several months. Looks like it is currently tagged "Wait for Category Feature".

In the meantime, make sure you are adding it to the Library in your *home* folder, not the root library.

Try these steps:
1. With the Finder active, click on the "Go" menu in the toolbar, and then select "Go to Folder..."
2. Paste this in exactly: `~/Library/Application Support/Franz/recipes/`
3. You will likely need to create the `dev` folder
4. [Download the binary from here](https://github.com/brianjohnhanna/mightytext-franz-recipe/archive/master.zip), unzip and add to the dev folder
5. Enjoy!

**Comment by MijoBarbaric** [comment]
@brianjohnhanna That worked like a charm, thank you very much!
