### ISSUE TITLE
Franz 4 does not show its icon in the indicator menu

### ISSUE THREAD

**Issue by Lazza** [meetfranz/plugins#14]
I am using Ubuntu 16.04 and the beta version of Franz (4.0.0) does not show an indicator menu icon. It was working with Franz 3.

**Comment by ffflorian** [comment]
With Franz 4.0.2 on Ubuntu 15.10 x64 it is working for me.

**Comment by adlk** [comment]
@Lazza please use the issues here for Plugin related issues only.
For feedback, bug reports, ... please use http://franz.zendesk.com

**Comment by Lazza** [comment]
@adlk ok.

Actually I didn't notice that Zendesk super-small link hidden under a generic "Get support" label. Besides, that platform doesn't look like a public bug tracker at all.

> Sometimes it's working and sometimes not

Same for me.
