### ISSUE TITLE
[Deploy] Office 365 Outlook Web App 

### ISSUE THREAD

**Issue by adambirds** [meetfranz/plugins#14]
### Service
Office 365 Outlook Web App

### Link to your repository
https://github.com/adambirds/recipe-office365-owa

### Additional Information
This is the recipe for Outlook Web App for Office 365

**Comment by adlk** [comment]
Please do a little clean up before I'm going to deploy the service
https://github.com/adambirds/recipe-office365-owa/issues/3

**Comment by adambirds** [comment]
@adlk this has been done in adambirds/recipe-office365-owa/issues/3

**Comment by mackbrowne** [comment]
subscribed to this thread.  Please let me know if you need someone to test.

**Comment by adambirds** [comment]
@mackbrowne feel free to test, just clone the repo and add to %appdata%\Franz\recipes\dev and then restart Franz. I tested and got no issues, but always worth a second test.

**Comment by mackbrowne** [comment]
Neat, I will do this hopefully before the end of today!

I can help test, but I also get the feature earlier :) it's win - win

**Comment by adlk** [comment]
Deployed, thanks for your contribution.
