### ISSUE TITLE
Blank screen/404 on Discord

### ISSUE THREAD

**Issue by huang-jy** [meetfranz/plugins#141]
Starting today, I have been getting a black screen in Discord.

![image](https://user-images.githubusercontent.com/2756283/37695529-00b9d76c-2cc8-11e8-97a6-449c79ab8a0b.png)

Reloading the service then gives me a 404

![image](https://user-images.githubusercontent.com/2756283/37695533-08f3e314-2cc8-11e8-8771-d6ea074d5bc1.png)

Adding a new copy of it has the same effect.

Logging in via the official app or the web version manually works.

**Comment by huang-jy** [comment]
Also, the linux version seems fine

**Comment by jonhil** [comment]
Maybe you should issue it in this repo https://github.com/meetfranz/recipe-discord

**Comment by huang-jy** [comment]
Oh I forgot this was still open -- I'll close it, it's not an issue any longer
