### ISSUE TITLE
Weechat Frontend Glowing Bear Integration

### ISSUE THREAD

**Issue by mightyBroccoli** [meetfranz/plugins#15]
I am not capable of making such thing but my question would be if there is any interest in embedding such a system into Franz.

[Github: Glowing Bear](https://github.com/glowing-bear/glowing-bear)

**Comment by rnyberg** [comment]
I've been bugging them to include this for ages now. Feels weird that they ignore since it's a relatively simple app to include.

**Comment by rnyberg** [comment]
https://github.com/rnyberg/franz-glowingbear-plugin
