### ISSUE TITLE
Unread notifications without counts

### ISSUE THREAD

**Issue by bexelbie** [meetfranz/plugins#150]
Can we provide an unread notification similar to the built-in slack integration that would allow sites that either don't provide an unread count, or don't provide one on every page to at least alert?

**Comment by bexelbie** [comment]
The setBadge function will take text, it appears.  It would be nice to have this still put the indicator on the icon.

~~~
Franz.setBadge("&middot;");
~~~

**Comment by bexelbie** [comment]
This should also get documented

**Comment by BehindTheMath** [comment]
You can use the `indirectMessages` parameter:

```
Franz.setBadge(false, true);
```

**Comment by bexelbie** [comment]
Cool.  Thank you.
