### ISSUE TITLE
Unable to answer Skype calls

### ISSUE THREAD

**Issue by bahgoogen** [meetfranz/plugins#156]
Seemingly unable to answer incoming skype calls. Nothing happens when the buttons are pressed.
 Mac OSX 10.11.3 and using Franz v4.0.4

**Comment by ghost1227** [comment]
![screen shot 2017-01-31 at 10 50 36 pm](https://cloud.githubusercontent.com/assets/36433/22497825/cb3717a6-e819-11e6-9c5a-05840e3a58a6.png)

**Comment by ghost1227** [comment]
<img width="590" alt="screen shot 2017-02-01 at 1 00 01 am" src="https://cloud.githubusercontent.com/assets/36433/22497833/d345c3b6-e819-11e6-9041-7e66f5fbf646.png">

**Comment by bahgoogen** [comment]
Thanks! Did not see that as i haven't had to edit my skype tab before.
Problem solved.
