### ISSUE TITLE
[Deploy] Notion Support

### ISSUE THREAD

**Issue by wcchristian** [meetfranz/plugins#158]
### Service
This recipe is to allow use of Notion within Franz. Notion is a really awesome notetaking and project management and general productivity tool.

https://notion.so

### Link to your repository
https://github.com/wcchristian/franz-notion-recipe

**Comment by jonhil** [comment]
Duplication of https://github.com/meetfranz/plugins/issues/99

**Comment by wcchristian** [comment]
#99 Doesn't handle notifications while this one does.

**Comment by rfgamaral** [comment]
@wcchristian Did you remove your repo? Why?
