### ISSUE TITLE
[Deploy] Workplace Messenger

### ISSUE THREAD

**Issue by jovanovski** [meetfranz/plugins#17]
### Service
Workplace Messenger - The enterprise version of Facebook for companies

### Link to your repository
https://github.com/jovanovski/WorkplaceChatForFranz5

**Comment by adlk** [comment]
There is already a version of workplace in Franz. Please take a look here: #8

**Comment by jovanovski** [comment]
Ah, didn't see it a while back. Awesome, keep up the good work guys!
