### ISSUE TITLE
[Request] Grammarly 

### ISSUE THREAD

**Issue by dbogdanov** [meetfranz/plugins#184]
What about having a recipe for [Grammarly](https://grammarly.com/)?

**Comment by oliver-gramberg** [comment]
I use Grammarly. I can't see it as a messaging app, though. Why do you want it in Franz? Consider
* a bookmark in your favourite browser
* using https://github.com/jvdmeij/recipe-franz-website/archive/master.zip

**Comment by dbogdanov** [comment]
@oliver-gramberg Franz is not only a messaging app. There are plugins for Google Calendar, Google Keep, Evernote, Todoist, Toggle, and Google Translate, among others.

**Comment by hoektoe** [comment]
I would also like a recipe for Grammarly inside the macOS app of Franz

**Comment by salerpsan** [comment]
Hey guys!
This could be awesome, also could you tell me how to add a recipe? I tried on macOS Mojave creating the folders but doesn't load.

**Comment by ZeryOs** [comment]
> Hey guys!
> This could be awesome, also could you tell me how to add a recipe? I tried on macOS Mojave creating the folders but doesn't load.

The standard directories:
Mac: ~/Library/Application Support/Franz/recipes/dev/
Windows: %appdata%/Franz/recipes/dev/
Linux: ~/.config/Franz/recipes/dev
----------------------------------
I'm so IN for this plugin.

**Comment by akmalkadi** [comment]
here we go : https://github.com/meetfranz/plugins/issues/426

**Comment by dbogdanov** [comment]
This is amazing, thanks a lot!!!

**Comment by jamieCart** [comment]
hiya,
this is great. I managed to get it installed and running, however, the main reason for me to get Grammarly in Franz was to use its functionality in other apps ie while typing in Gmail for Grammarly to do spell/grammar checks, does anyone know if this is possible?

Best,
J
p.s. I am completely new to coding of any kind

**Comment by mysticaltech** [comment]
@jamieCart Rambox paid version has that option! Basically you can use any chrome extensions with it.
