### ISSUE TITLE
Grouping/Organisation of services/tabs

### ISSUE THREAD

**Issue by Decipher** [meetfranz/plugins#19]
I currently have 10 services/tabs in Franz, and given the addition of plugins I expect that number to rapidly increase.

It would be ideal to have some sort of Grouping/Organisation abilities for services/tabs.

I have a few thoughts on how it could be implemented:

- Workspaces/Tags; Ability set a workspace/tag per service so you can swap between relevant services for Work, Social, etc. All items not tagged for the current workspace would be disabled and hidden.

- Grouping; Ability to group like services into a single tab, so all Google Calendars could live under a single tab with a dropdown arrow to select specific integration.

- Horizontal scrolling or Vertical tabs; Instead of increasing the height of the tabs bar as it overflows, allow for either horizontal scrolling or a collapsible service sidebar (ala Airmail and other similar UIs). Possibly make the behaviour configurable.

Hope you consider something here, and even better, hope you consider entirely open-sourcing the project, because I'm sure there are plenty of developers that would love to get involved.

**Comment by ffflorian** [comment]
Good idea, but I think this should be reported to [@FranzSupport](https://twitter.com/franzsupport) or at http://franz.zendesk.com since this repository is related to plugins only. See [#14](https://github.com/meetfranz/plugins/issues/14#issuecomment-243715820).

**Comment by Decipher** [comment]
My bad, I had looked for the support channel but had no luck finding it. Thanks.
