### ISSUE TITLE
[Deploy] Teamwork Projects

### ISSUE THREAD

**Issue by koma-private** [meetfranz/plugins#19]
### Service
[Teamwork Projects](https://www.teamwork.com)

### Link to your repository
https://github.com/koma-private/franz_v5_recipes/tree/master/teamwork-projects

### Additional information
- This recipe is ported from [V4 plugin](https://github.com/meetfranz/plugins-legacy/tree/master/teamwork-projects)
- Original Author of V4 plugin : [Retzudo](https://github.com/Retzudo/)

**Comment by adlk** [comment]
Deployed, thanks for your contribution.
