### ISSUE TITLE
[Deploy] Android Messages

### ISSUE THREAD

**Issue by dweinber** [meetfranz/plugins#192]
A simple recipe for Android Messages, similar other messengers, including unread badge count.

### Service
[Android Messages](https://messages.android.com/)

### Link to your repository
https://github.com/dweinber/franz-recipe-android-messages

### Additional Information
Already created a PR: https://github.com/meetfranz/plugins/pull/169

**Comment by FilipMalczak** [comment]
I was thinking to do that myself, but the way you've  figured out "unread" badge is really neat. Respect.

**Comment by FilipMalczak** [comment]
Duplicated by #164 and #170 . I personally like this approach best.

**Comment by sammykumar** [comment]
works well! was about to create my own recipe but then I found this! great work

**Comment by dweinber** [comment]
I guess this can be closed as the [PR](https://github.com/meetfranz/plugins/pull/169) is merged.
