### ISSUE TITLE
[Deploy] Gridle

### ISSUE THREAD

**Issue by fenilgandhi** [meetfranz/plugins#226]
Gridle Recipe
 
Service Name : Gridle 
Link to repo   :  https://github.com/fenilgandhi/franz-recipe-gridle
Link to application : https://app.gridle.io/

**Comment by fenilgandhi** [comment]
Also i am interested in porting the old plugins to the new recipes. So shall i submit a pull request or create an issue over here ?
@mordaroso @davereid @BrianGilbert @riddla

**Comment by BrianGilbert** [comment]
I don't have access to approve pull requests, but I will advise that your repo name doesn't match the convention.

It should be franz-recipe-gridle

**Comment by fenilgandhi** [comment]
Ok, i have updated it. Thanks for pointing out.
