### ISSUE TITLE
[DEPLOY] GaduGadu

### ISSUE THREAD

**Issue by wzieciak** [meetfranz/plugins#23]
### Service
This recipe is for the GaduGadu - the most popular polish communicator of the 00's!

### Link to your repository
https://github.com/W-Zieciak/recipe-franz-gadugadu

**Comment by adlk** [comment]
Deployed, thanks for your contribution.

**Comment by wzieciak** [comment]
For now, Franz can't load this recipe, when I try to add it to my instance. Everything is alright deployed?
