### ISSUE TITLE
Skype not seeing microphone/camera

### ISSUE THREAD

**Issue by mrandreastoth** [meetfranz/plugins#279]
Skype is not seeing microphone/camera whilst other plugins such as Messenger do.

### Service
Skype

**Comment by fabiancz** [comment]
Possibility to changing user agent in Franz is the solution (https://github.com/meetfranz/franz/issues/1060).

If I change user agent in Chrome "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Franz/5.0.0 Chrome/69.0.3497.106 Electron/4.0.4 Safari/537.36" (which is sending my Franz 5.0.0), then I'm not able to click on phone icon on https://preview.web.skype.com/ website.
But original Chrome user agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36" works!

When "Electron/4.0.4" is present in user agent string, then Skype preview web disable phone icon.

**Comment by morgej** [comment]
Any update on this issue?

**Comment by adlk** [comment]
The fix was deployed. Please just search for updates in settings.

**Comment by morgej** [comment]
I am not seeing a new update and Skype is not seeing my mic/speakers.

Please advise.  Thanks.

![image](https://user-images.githubusercontent.com/13367152/56363840-14f6ad80-61bb-11e9-9dbc-64723f42a0fd.png)

**Comment by fabiancz** [comment]
My services was refreshed somehow, and it works now. What about yours, Morgej?

**Comment by morgej** [comment]
Excellent!  Skype voice calls are now working.
