### ISSUE TITLE
No support currently for "Normal" Facebook (including Facebook Workplace)

### ISSUE THREAD

**Issue by huang-jy** [meetfranz/plugins#289]
We have support in V5 for Facebook Messenger and Facebook Pages, but not for "Normal" Facebook (this includes Facebook Workplace)

We can work around this as a VERY crude hack by adding "Facebook Pages", linking it with either a fake/duff page and then using that error page to get the FB homepage, but it would be much easier to have it natively.

This hack doesn't work for Workplace.

### Service
Facebook
Facebook Workplace

### Link to your repository
N/A

### Additional Information
None

**Comment by theophanemayaud** [comment]
I also think this would be really useful.

**Comment by theophanemayaud** [comment]
In fact, after playing around, I found that the url checked by the facebook pages recipe is https://facebook.com/{teamId}/inbox (found through [https://github.com/meetfranz/recipe-facebook-pages/blob/master/package.json](https://github.com/meetfranz/recipe-facebook-pages/blob/master/package.json)
Therefore you can use the team name index.php=? for the service, which essentially brings you to the main facebook page !!!
![image](https://user-images.githubusercontent.com/25605953/59620255-b1dab600-912c-11e9-9947-dd676be1083f.png)

**Comment by huang-jy** [comment]
Closing due to issue being over a year old
