### ISSUE TITLE
rocket.chat not working?

### ISSUE THREAD

**Issue by alecive** [meetfranz/plugins#3]
Hello,

I am trying to create my custom plugin by basing mine on rocket.chat. I tried to add the rocket.chat plugin in `.config/Franz/Plugins` (I'm on linux), but it does not seem to be working: I click on the button to configure the new service, and I don't get the usual popup window that asks to give the service a name or mute all sounds.

PS: yes I am on Franz 4.0.0

**Comment by alecive** [comment]
If I launch franz from terminal, I do not get any error.

**Comment by adlk** [comment]
Thanks for reporting this. There is a bug in the current version that will be fixed asap.

**Comment by alecive** [comment]
Ok thank you! I am really looking forward to this. I have been also experiencing other issues with Franz 4.0.0 (but I am sick of opening tickets - GitHub issues would be much better!).

E.g.:
 1. if I un-tick the Launch Franz on start button, the app completely ignores it
 2. there is no tray icon any more (ticket already opened)

**Comment by alecive** [comment]
@adlk still, rocket.chat is not working as of now.

**Comment by e-minguez** [comment]
It doesn't work for me neither, otherwise, the app is awesome!

**Comment by frank0718** [comment]
mattermost is not working too, wait to be fixed as soon as possible
