### ISSUE TITLE
[Deploy] Instagram

### ISSUE THREAD

**Issue by adambirds** [meetfranz/plugins#30]
### Service
Instagram

### Link to your repository
https://github.com/adambirds/recipe-instagram

### Additional Information
This is a plugin for Instagram

**Comment by adambirds** [comment]
Is this getting added?

**Comment by m435tr0d** [comment]
this is great that it shows instagram web interface, but it doesn't really allow for messaging which is kind of the point of franz. Without direct messaging working what is the real point?

**Comment by martin-braun** [comment]
Well, someone built a real desktop client for instagram that allows chatting: https://github.com/ifedapoolarewaju/igdm

This is an Electron app, so it should be possible to convert this to a plugin for Franz, it should not?

**Comment by itripley** [comment]
did the Instagram electron app work? if it did, how?

**Comment by martin-braun** [comment]
@adambirds can you please re-open the issue, so it gets more attention? You are not the only one who wants this.


@afonsocarmo 

it uses the same "private" Instagram API like the official Instagram app. I think the most interesting file here is https://github.com/ifedapoolarewaju/igdm/blob/master/main/instagram.js which shows all available operations using its client. 

Someone else built the API client the author of the chat tool is using: https://github.com/ifedapoolarewaju/instagram-private-api

if the tool still works (I haven't test it), someone could require this api and communicate with Instagram the same way like the author did in the first link I posted. It would be useful to first build a web version out of his implementation and the Franz plugin in the last step.

His tool could be tested here: https://igdm.me/


Least but not last, the most successful persons on this topic would be the ones who built the API or the chat tool itself. 
@IvanMMM @ifedapoolarewaju

**Comment by adambirds** [comment]
I closed this because I am no longer using Franz or interested in spending any more development time on it. If you would like to look at it further then please feel free to fork the repo and then work from there.

**Comment by martin-braun** [comment]
> I closed this because I am no longer using Franz or interested in spending any more development time on it. If you would like to look at it further then please feel free to fork the repo and then work from there.

You don't need to spend any more time to it, but please re-open and unsubscribe this issue, so it gets some more attention.

Thank you!
