### ISSUE TITLE
Auth Popup

### ISSUE THREAD

**Issue by carlosefonseca** [meetfranz/plugins#31]
I'm trying to create a plugin for Asana, with Google Auth but I'm having some problems. (OSX here)

When I click the Asana button to open the Google Auth, a new tab opens. It actually showed content once but now it's just blank. I think it's because it's already authenticated and trying to go back to the Asana tab.
I've tried to set the `popup` config in multiple ways but it's making no difference. Now I'm even trying with `.*`. It always opens in a tab inside Franz. If I use `"popup": []` it opens in Safari.

This is my current config.
```
  "config": {
    "serviceURL": "https://app.asana.com",
    "serviceName": "asana",
    "message": "",
    "popup": ["^https:\/\/accounts.google.com\/.*"],
    "hasNotificationSound": true,
    "hasIndirectMessages": false,
    "hasTeamID": false,
    "customURL": false,
    "hostedOnly": false,
    "webviewOptions": {
      "disablewebsecurity": ""
    },
    "openDevTools": true
  }
```

Ideas?
Thanks!

**Comment by carlosefonseca** [comment]
Logging in with username and password works, so I'm probably sticking with that…

**Comment by adlk** [comment]
3rd party logins are not implemented yet. We have it on our todo list but it's to early to give an ETA.
