### ISSUE TITLE
[Deploy] mailbox.org

### ISSUE THREAD

**Issue by jonhil** [meetfranz/plugins#33]
### Service
[mailbox.org](https://www.mailbox.org) is a privacy focused email provider.

### Link to your repository
https://github.com/jonhil/recipe-franz-mailbox.org

**Comment by adlk** [comment]
Please review this and your other submissions as you've just copied the orat.io boilerplate code to display the notification badges. This however just works with orat.io as every service needs specific optimizations. 
Not doing this optimization just lead to poor UX and user complaints.

**Comment by jonhil** [comment]
Ok, thanks for your feedback.
I'll let you know once I finished them...

**Comment by jonhil** [comment]
@adlk I reviewed my submissions and everything (unread count etc.) is working flawless for me now.
Thanks for your awesome work btw ;)

**Comment by adlk** [comment]
Thanks for updating the recipe.

---

Deployed, thanks for your contribution.
