### ISSUE TITLE
[Deploy] Twitch Chat

### ISSUE THREAD

**Issue by colinodell** [meetfranz/plugins#36]
### Service
[Twitch.tv](https://www.twitch.tv) chat

### Link to your repository
<https://github.com/colinodell/franz-twitch>

### Additional Information

Forked from the proposed Franz 4 recipe.

Users who want to add Twitch chat will be getting the team id from URLs like <https://go.twitch.tv/sovietwomble>.  I've therefore defined `https://go.twitch.tv/` as the `urlInputPrefix` even though that config option is not yet present on the configuration screen.

![image](https://user-images.githubusercontent.com/202034/32397781-ed0a1c6c-c0c1-11e7-8d59-5ec4f0c0cd3c.png)

**Comment by adlk** [comment]
Deployed, thanks for your contribution.
