### ISSUE TITLE
[Deploy] Roundcube

### ISSUE THREAD

**Issue by jonathanjuursema** [meetfranz/plugins#41]
### Service
Roundcube webmail client

### Link to your repository
The recipe can be found [here](https://github.com/jonathanjuursema/franz-roundcube).

### Additional Information
Roundcube doesn't have any hi res or vector format logo around that I could find, so I included a basic e-mail icon. If anyone knows where I can find a vector icon, please let me know. :)

**Comment by adlk** [comment]
Where does this icon come from or what's the license of it?

**Comment by jonathanjuursema** [comment]
Icon attribution and license info is included in the [recipe](https://github.com/jonathanjuursema/franz-roundcube/blob/master/ICON_LICENSE). The color modifications are done by me and in the public domain.

**Comment by adlk** [comment]
Oh sorry, I've missed that!

---

Deployed, thanks for your contribution.

**Comment by jonathanjuursema** [comment]
No prob, thanks for the inclusion. :)
