### ISSUE TITLE
[Deploy] Google Allo

### ISSUE THREAD

**Issue by ldrrp** [meetfranz/plugins#5]
### Service
Google Allo Web

### Link to your repository
https://github.com/SiloCityLabs/recipe-franz-googleallo

**Comment by adlk** [comment]
Thanks for your plugin!
I'm not going to deploy this right now as it would be a service duplicate. Instead I'm waiting for the settings API to be finished to merge your plugin with the existing one. . This allows us to add a setting to enable/disable the dark mode.

**Comment by ldrrp** [comment]
um, do you mean this for the Telegram service? i think you posted under the wrong bug

**Comment by ldrrp** [comment]
There is currently no Allo plugin for either 4.x or 5.x

**Comment by adlk** [comment]
Deployed. Thanks for your contribution.
