### ISSUE TITLE
[Deploy] Threema

### ISSUE THREAD

**Issue by AnnaDamm** [meetfranz/plugins#54]
### Service
[Threema](https://threema.ch)

### Link to your repository
https://github.com/Arany/franz-recipe-threema

### Additional Information
I did not find a publicly available big enough icon, so I took the svg from https://github.com/FortAwesome/Font-Awesome/issues/7057#issuecomment-154059526 and then changed the colors a bit.

Also, the login is not saved between sessions. I guess it COULD be done, but it would decrease security, as some data is apparently saved encrypted in local storage. Setting a password automatically and using it to login..

**Comment by adlk** [comment]
Deployed, thanks for your contribution.
