### ISSUE TITLE
Support for Shout IRC.

### ISSUE THREAD

**Issue by Decipher** [meetfranz/plugins#6]
This is a personal request and incentive for myself to look at contributing.

Shout IRC (http://shout-irc.com/) client is a NodeJS IRC client. My intention is for a self hosted version of Shout IRC to be used, much like Mattermost.

Will look at what's involved in any upcoming free time.

**Comment by Decipher** [comment]
Going to close this, the work has been done. PR will come pending #7

**Comment by Neavend** [comment]
Whenever I try to add this service to Franz the "Add Shout" button does not seem to be working
(Franz version 4.0.4 - No traces in error.log / user.log)
