### ISSUE TITLE
[Deploy] Outlook

### ISSUE THREAD

**Issue by woutervs** [meetfranz/plugins#71]
Similar to Office 365 Outlook

### Service
Outlook Live

### Link to your repository
https://github.com/woutervs/MeetFranz-Outlook

### Additional Information
Notifications on inbox work

**Comment by adlk** [comment]
I've discovered a few issues when checking the recipe:

- **package.json:** Change name to: Outlook
- **icon**: Please provide a png as well
- **license**: is referencing _Adam Birds_

**Comment by woutervs** [comment]
Updated and checked in.

**Comment by adlk** [comment]
Deployed, thanks for your contribution.
