### ISSUE TITLE
[ Deploy ] Plurk

### ISSUE THREAD

**Issue by irvin** [meetfranz/plugins#73]
### Service

Plurk (https://plurk.com) is a popular social network service in [Taiwan, India and Japan](https://www.alexa.com/siteinfo/plurk.com).
https://en.wikipedia.org/wiki/Plurk

### Link to your repository

[https://github.com/irvin/Plurk-for-Franz](https://github.com/irvin/Plurk-for-Franz)

**Comment by adlk** [comment]
Plurk is already available in Franz
<img width="590" alt="bildschirmfoto 2017-11-25 um 21 12 31" src="https://user-images.githubusercontent.com/3265004/33234337-65aa2378-d225-11e7-8004-3fa2561eb2b5.png">

**Comment by irvin** [comment]
good to know, thanks!
