### ISSUE TITLE
Custom plugin: Problem with `hasTeamID`

### ISSUE THREAD

**Issue by Retzudo** [meetfranz/plugins#9]
I'm trying to create a custom plugin for [Teamwork](https://www.teamwork.com/) but I'm having some issues with the `hasTeamID` option in `package.json`. 

```json
{
  "name": "Teamwork",
  "version": "0.1.0",
  "description": "Teamwork",
  "main": "index.js",
  "author": "Retzudo",
  "license": "MIT",
  "config": {
    "serviceURL": "https://{teamID}.teamwork.com",
    "serviceName": "Teamwork",
    "popup": [],
    "hasNotificationSound": true,
    "hasedirectMessages": false,
    "hasTeamID": true,
    "customURL": false,
    "hostedOnly": false,
    "webviewOptions": {},
    "openDevTools": false
  }
}
```

To rule out any mistakes I copy-pasted `package.json`, `index.js` and `webview.js` from [here](https://github.com/meetfranz/plugins/blob/develop/docs/integration.md), added my own `icon.png` and `icon.svg`, and modified `package.json` by changing `name`, `version`, `description`, `author`, `config.hasTeamID` and removing `config.message`. The JSON above does **not** work in that my custom plugin appears, but clicking it does nothing.

If I now set `hasTeamID` to `false`, I can click my plugin, enter a name and it's added as a new tab (which doesn't load properly because it tries to fetch the URL with the placeholder still in place, which is fine).

I'm not sure what is happening.

PS: I've attached the whole plugin if that helps: [Teamwork.zip](https://github.com/meetfranz/plugins/files/444461/Teamwork.zip)

**Comment by Lazza** [comment]
This looks similar to #7.

**Comment by adlk** [comment]
Hi @Retzudo, we've just started rolling out Franz 4.0.3 where this issue is fixed. However, we recommend adding a `wording` flag. This makes it more straightforward to understand what the team id is for. 

```json
{
  "name": "Teamwork",
  "version": "0.1.0",
  "description": "Teamwork",
  "main": "index.js",
  "author": "Retzudo",
  "license": "MIT",
  "config": {
    "serviceURL": "https://{teamID}.teamwork.com",
    "serviceName": "Teamwork",
    "popup": [],
    "hasNotificationSound": true,
    "hasedirectMessages": false,
    "hasTeamID": true,
    "customURL": false,
    "hostedOnly": false,
    "webviewOptions": {},
    "openDevTools": false,
    "wording": {
        "url": "teamwork.com",
        "team": "Teamwork"
    }
  }
}
```

![screenshot](https://cloud.githubusercontent.com/assets/3265004/18272818/49d7bbaa-743a-11e6-9b3d-5a461d0d5863.png)
