### ISSUE TITLE
[Deploy] Google Calendar

### ISSUE THREAD

**Issue by rherwig** [meetfranz/plugins#9]
### Service
Google Calendar

### Link to your repository
https://github.com/rherwig/franz-5-googlecalendar

### Additional Information
This is a port of the legacy plugin with only slightly refined code style.

**Comment by timschlechter** [comment]
:+1:

**Comment by Horscht** [comment]
sorry, how to install a plugin in franz 5 on mac please?

ah ok, have found it: must create a folder called 'dev' in the recipes folder (../Users/[username]/Library/Application Support/Franz) and in this put the googlecalendar folder ... restart franz ...

**Comment by adlk** [comment]
Deployed, thanks for your contribution.
